### PR TITLE
GraphicsPackWindow2: Use UTF8

### LINKED ISSUE #801: [Bug Report] Graphic Packs don't accept Certain Symbols.
Hello, I would like to report a couple of problems with the Graphics Pack System:

Visual Issue:
If your Graphic Pack rules.txt file (name, path or description) contains problematic symbols, Cemu's Graphic Pack Manager will display garbled characters instead.

Usability Issue:
If your Graphic Pack path contains problematic symbols, Cemu will not let you enable that Graphic Pack.
(When you open Cemu again, you will see that your Graphic Pack has been automatically deactivated).

 Example of problematic symbols:
  · Accute Accent: ´
  · N with Tilde: ñ 
  · Upside Down Question/Exclamation Mark: ¡ ¿

 On the other hand, there are other symbols that (unlike the above), will not cause any problems in Cemu:

 Example of not problematic symbols:
  · Parentheses: ( )
  · Square Brackets: [ ]
  · Downwards Question Mark: ?
  · Downwards Exclamation Mark: !
  · Grave Accent: `

These two problems have occurred in every version I have tested, including the most recent to date: Cemu 2.0-36 (Experimental). (Commit hash: f48ad6a)

Because of this, I would like to request the correction of these problems, so that such symbols can be entered without causing issues when they are used.
Thank you very much.

Issue

### PR DESCRIPTION
**Pull request by goeiecool9999**
Attempt to fix #801
may also affect #537

### CODE REVIEW

File: src/gui/GraphicPacksWindow2.cpp [hunk 1]
```diff
@@ -386,28 +388,29 @@ void GraphicPacksWindow2::LoadPresetSelections(const GraphicPackPtr& gp)
 		{
 			continue;
 		}
-					
-		wxString label(category.empty() ? _("Active preset") : wxString(category));
+
+		wxString categoryWxStr = wxHelper::FromUtf8(category);
+		wxString label(category.empty() ? _("Active preset") : wxString(categoryWxStr));
```
Comment (Exzap) [inline src/gui/GraphicPacksWindow2.cpp:393]: Small nitpick but since `categoryWxStr` is already a wxString it shouldn't be necessary to wrap it in another `wxString(...)` constructor

Comment (goeiecool9999) [reply src/gui/GraphicPacksWindow2.cpp]: Good catch
